// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4rn9bfQMHTCfw2XI2EDUIDwQsE0khBXE',
    appId: '1:759472035023:web:e6d991c0d4aa8465bf13ba',
    messagingSenderId: '759472035023',
    projectId: 'chatmessenger-2031b',
    authDomain: 'chatmessenger-2031b.firebaseapp.com',
    storageBucket: 'chatmessenger-2031b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0WYFkSz822Jjcs-HLAm1o_mpBMvLN2A',
    appId: '1:759472035023:android:cde003f1b0cea827bf13ba',
    messagingSenderId: '759472035023',
    projectId: 'chatmessenger-2031b',
    storageBucket: 'chatmessenger-2031b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4MTNoebjcEFQdH9-kPdx2E_xKyFHDmaM',
    appId: '1:759472035023:ios:112db8ec1afba132bf13ba',
    messagingSenderId: '759472035023',
    projectId: 'chatmessenger-2031b',
    storageBucket: 'chatmessenger-2031b.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4MTNoebjcEFQdH9-kPdx2E_xKyFHDmaM',
    appId: '1:759472035023:ios:112db8ec1afba132bf13ba',
    messagingSenderId: '759472035023',
    projectId: 'chatmessenger-2031b',
    storageBucket: 'chatmessenger-2031b.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4rn9bfQMHTCfw2XI2EDUIDwQsE0khBXE',
    appId: '1:759472035023:web:90929adb77915099bf13ba',
    messagingSenderId: '759472035023',
    projectId: 'chatmessenger-2031b',
    authDomain: 'chatmessenger-2031b.firebaseapp.com',
    storageBucket: 'chatmessenger-2031b.firebasestorage.app',
  );
}

